# Generated by Django 3.2.5 on 2021-10-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoAdministrador', models.ImageField(upload_to='core', verbose_name='fotoAdministrador')),
                ('dniAdministrador', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'administrador',
                'verbose_name_plural': 'administradores',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('denominacionSocial', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=45)),
                ('cif', models.CharField(max_length=45)),
                ('actividad', models.CharField(max_length=100)),
                ('idAdministrador', models.OneToOneField(on_delete=models.SET('sin administrador'), primary_key=True, related_name='EmpresaIdAdministrador', serialize=False, to='core.administrador')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
